### ISSUE TITLE
SVG Regression: Intrinsic Ratios

### ISSUE THREAD

**Issue by mikerockett** [Kozea/WeasyPrint#1417]
I am using the CLI to build my PDFs, which contain both inline and `<img/>` SVGs, which may or may not have an intrinsic height and/or width. Instead, all images are sized using CSS-only.

After updating to 53-stable, I am now receiving the following error:

> File "/usr/local/lib/python3.9/site-packages/weasyprint/layout/preferred.py", line 122, in min_max
> ratio = box.replacement.intrinsic_ratio
> **AttributeError: 'SVGImage' object has no attribute 'intrinsic_ratio'**

I am assuming 2e96bdee356b7971446861ecd217050d3c8e91f9 has something to do with it. Does this mean I must now specify these dimensions in my SVG files? The problem here is that these SVGs are user-provided, which means I would need to build a processor to add them upon upload.

Or perhaps I am missing something…?

**Comment by liZe** [comment]
Hello!

I have good news: this issue has already been fixed by 2e96bde. We’ll have to release a new version soon :wink:.

**Comment by mikerockett** [comment]
Ah right, so that commit was actually the fix, not the problem. 😅  Great stuff, I'll wait for the release then.

**Comment by mikerockett** [comment]
@liZe – Do you have a date for when the next release comes out? I'm using it in a freight forwarding system which is scheduled to go live next month. We could revert to v52, but I think that would be a pointless exercise… Thanks!

**Comment by liZe** [comment]
@mikerockett Version 53.1 has been released today!

**Comment by mikerockett** [comment]
Fantastic, thanks @liZe!
