### ISSUE TITLE
weasyprint not working in python 3.6 version 64 bit 

### ISSUE THREAD

**Issue by stephinjose08** [Kozea/WeasyPrint#1709]
I'm install  weasyprint for downloading invoice as part of ecommerce project using django.I install weasyprint using pip after installing  weasyprint I also installed gtk  after write down the pdf generation code make the server is running made an error which is 

"TypeError: __new__() missing 6 required positional arguments: 'xx', 'xy', 'yx', 'yy', 'dx', and 'dy' "

how can I solve it ? I already search anywhere using internet but did'nt get proper answer

if anyone knows about this please help me

**Comment by liZe** [comment]
Hi!

Could you please give us the whole stacktrace?

**Comment by stephinjose08** [comment]
Exception in thread django-main-thread:
Traceback (most recent call last):
  File
"D:\EcommerceProject\venv\lib\site-packages\django\urls\resolvers.py", line
604, in url_patterns
    iter(patterns)
TypeError: 'module' object is not iterable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File
"c:\users\lenovo\appdata\local\programs\python\python36\lib\threading.py",
line 916, in _bootstrap_inner
    self.run()
  File
"c:\users\lenovo\appdata\local\programs\python\python36\lib\threading.py",
line 864, in run
    self._target(*self._args, **self._kwargs)
  File
"D:\EcommerceProject\venv\lib\site-packages\django\utils\autoreload.py",
line 64, in wrapper
    fn(*args, **kwargs)
  File
"D:\EcommerceProject\venv\lib\site-packages\django\core\management\commands\runserver.py",
line 118, in inner_run
    self.check(display_num_errors=True)
  File
"D:\EcommerceProject\venv\lib\site-packages\django\core\management\base.py",
line 423, in check
    databases=databases,
  File
"D:\EcommerceProject\venv\lib\site-packages\django\core\checks\registry.py",
line 76, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File
"D:\EcommerceProject\venv\lib\site-packages\django\core\checks\urls.py",
line 13, in check_url_config
    return check_resolver(resolver)
  File
"D:\EcommerceProject\venv\lib\site-packages\django\core\checks\urls.py",
line 23, in check_resolver
    return check_method()
  File
"D:\EcommerceProject\venv\lib\site-packages\django\urls\resolvers.py", line
416, in check
    for pattern in self.url_patterns:
  File
"D:\EcommerceProject\venv\lib\site-packages\django\utils\functional.py",
line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File
"D:\EcommerceProject\venv\lib\site-packages\django\urls\resolvers.py", line
611, in url_patterns
    raise ImproperlyConfigured(msg.format(name=self.urlconf_name)) from e
django.core.exceptions.ImproperlyConfigured: The included URLconf
'ecommerce.urls' does not appear to have any patterns in it. If you see
valid patterns in the file then the issue is probably caused by a circular
import.

this is when i make server running

**Comment by liZe** [comment]
Thank you.

> "D:\EcommerceProject\venv\lib\site-packages\fontTools\misc\transform.py", line 349, in <module>
> Identity = Transform()
> TypeError: __new__() missing 6 required positional arguments: 'xx', 'xy', 'yx', 'yy', 'dx', and 'dy'

This problem happens because of this feature: [`namedtuple`s allow default values](https://docs.python.org/3.7/whatsnew/3.7.html#collections).

This feature has been included in Python 3.7, and WeasyPrint (and its dependency fontTools here) doesn’t support Python 3.6 anymore. Actually, [Python 3.6 is now officially unsupported](https://endoflife.date/python), so you’ll have to use Python 3.7+ to fix this problem.

**Comment by stephinjose08** [comment]
Thanks a lot. for your valuable information
i so gratitude for spending your valuable time for me

**Comment by stephinjose08** [comment]
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File
"D:\EcommerceProject\venv\lib\site-packages\django\core\management\__init__.py",
line 419, in execute_from_command_line
    utility.execute()
  File
"D:\EcommerceProject\venv\lib\site-packages\django\core\management\__init__.py",
line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File
"D:\EcommerceProject\venv\lib\site-packages\django\core\management\base.py",
line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File
"D:\EcommerceProject\venv\lib\site-packages\django\core\management\base.py",
line 393, in execute
    self.check()
  File
"D:\EcommerceProject\venv\lib\site-packages\django\core\management\base.py",
line 423, in check
    databases=databases,
  File
"D:\EcommerceProject\venv\lib\site-packages\django\core\checks\registry.py",
line 76, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File
"D:\EcommerceProject\venv\lib\site-packages\django\core\checks\urls.py",
line 13, in check_url_config
    return check_resolver(resolver)
  File
"D:\EcommerceProject\venv\lib\site-packages\django\core\checks\urls.py",
line 23, in check_resolver
    return check_method()
  File
"D:\EcommerceProject\venv\lib\site-packages\django\urls\resolvers.py", line
416, in check
    for pattern in self.url_patterns:
  File
"D:\EcommerceProject\venv\lib\site-packages\django\utils\functional.py",
line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File
"D:\EcommerceProject\venv\lib\site-packages\django\urls\resolvers.py", line
602, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns",
self.urlconf_module)
  File
"D:\EcommerceProject\venv\lib\site-packages\django\utils\functional.py",
line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File
"D:\EcommerceProject\venv\lib\site-packages\django\urls\resolvers.py", line
595, in urlconf_module
    return import_module(self.urlconf_name)
  File
"c:\users\lenovo\appdata\local\programs\python\python36\lib\importlib\__init__.py",
line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in
_call_with_frames_removed
  File "D:\EcommerceProject\ecommerce\ecommerce\urls.py", line 25, in
<module>
    path('customadmin/',include("useradmin.urls")),
  File "D:\EcommerceProject\venv\lib\site-packages\django\urls\conf.py",
line 34, in include
    urlconf_module = import_module(urlconf_module)
  File
"c:\users\lenovo\appdata\local\programs\python\python36\lib\importlib\__init__.py",
line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in
_call_with_frames_removed
  File "D:\EcommerceProject\ecommerce\useradmin\urls.py", line 2, in
<module>
    from  useradmin import views
  File "D:\EcommerceProject\ecommerce\useradmin\views.py", line 18, in
<module>
    from weasyprint import HTML
  File "D:\EcommerceProject\venv\lib\site-packages\weasyprint\__init__.py",
line 325, in <module>
    from .css import preprocess_stylesheet  # noqa isort:skip
  File
"D:\EcommerceProject\venv\lib\site-packages\weasyprint\css\__init__.py",
line 27, in <module>
    from . import computed_values, counters, media_queries
  File
"D:\EcommerceProject\venv\lib\site-packages\weasyprint\css\computed_values.py",
line 17, in <module>
    from ..text.line_break import Layout, first_line_metrics, line_size
  File
"D:\EcommerceProject\venv\lib\site-packages\weasyprint\text\line_break.py",
line 18, in <module>
    from .fonts import font_features
  File
"D:\EcommerceProject\venv\lib\site-packages\weasyprint\text\fonts.py", line
17, in <module>
    from fontTools.ttLib import TTFont, woff2
  File
"D:\EcommerceProject\venv\lib\site-packages\fontTools\ttLib\woff2.py", line
14, in <module>
    from fontTools.ttLib.tables import ttProgram, _g_l_y_f
  File
"D:\EcommerceProject\venv\lib\site-packages\fontTools\ttLib\tables\_g_l_y_f.py",
line 9, in <module>
    from fontTools.misc.bezierTools import calcQuadraticBounds
  File
"D:\EcommerceProject\venv\lib\site-packages\fontTools\misc\bezierTools.py",
line 6, in <module>
    from fontTools.misc.transform import Identity
  File
"D:\EcommerceProject\venv\lib\site-packages\fontTools\misc\transform.py",
line 349, in <module>
    Identity = Transform()
TypeError: __new__() missing 6 required positional arguments: 'xx', 'xy',
'yx', 'yy', 'dx', and 'dy'

(venv) D:\EcommerceProject\ecommerce>


this is the error showing
