### ISSUE TITLE
V65 Flexbox child SVG issue

### ISSUE THREAD

**Issue by mike667** [Kozea/WeasyPrint#2415]
Hello. After upgrading to v65, the flexbox in my template is broken. It works well with v64. I'm not sure if it's related to [cssselect2](https://github.com/Kozea/cssselect2) or [WeasyPrint](https://github.com/Kozea/WeasyPrint)

```
image = box.replacement
            ^^^^^^^^^^^^^^^
AttributeError: 'FlexBox' object has no attribute 'replacement'
```

_Updated_
The problem in my template is with SVG - a child SVG causes a flexbox error.

```
<div style="display:flex">
  <svg height="100" width="100" xmlns="http://www.w3.org/2000/svg">
    <circle r="45" cx="50" cy="50" fill="red" />
  </svg>
</div>
```

**Comment by liZe** [comment]
Hi!

Thanks for the report.

Could you please share the whole stacktrace and a document that shows the problem? I can’t reproduce with your sample alone.

**Comment by Christoph-Wagner** [comment]
Assuming the `svg` has `display:block` somewhere, I have the same issue, and it also affects `img`s. In my case I can also live with `display: inline-block` as a workaround.

Minimal reproduction on Weasyprint 65:

```html
<!DOCTYPE html>
<html>
  <head>
    <title>Testcase</title>
    <style>
      div {
        display: flex;
      }
      img {
        display: block;
      }
    </style>
  </head>

  <body>
    <div>
      <img src="https://picsum.photos/200/300" />
    </div>
  </body>
</html>
```

Full stacktrace:

```
Traceback (most recent call last):
  File "weasyprint\__main__.py", line 201, in <module>
  File "weasyprint\__main__.py", line 194, in main
  File "weasyprint\__init__.py", line 265, in write_pdf
  File "weasyprint\__init__.py", line 222, in render
  File "weasyprint\document.py", line 253, in _render
  File "weasyprint\layout\__init__.py", line 130, in layout_document
  File "weasyprint\layout\page.py", line 966, in make_all_pages
  File "weasyprint\layout\page.py", line 906, in remake_page
  File "weasyprint\layout\page.py", line 647, in make_page
  File "weasyprint\layout\block.py", line 59, in block_level_layout
  File "weasyprint\layout\block.py", line 75, in block_level_layout_switch
  File "weasyprint\layout\block.py", line 124, in block_box_layout
  File "weasyprint\layout\block.py", line 723, in block_container_layout
  File "weasyprint\layout\block.py", line 525, in _in_flow_layout
  File "weasyprint\layout\block.py", line 59, in block_level_layout
  File "weasyprint\layout\block.py", line 75, in block_level_layout_switch
  File "weasyprint\layout\block.py", line 124, in block_box_layout
  File "weasyprint\layout\block.py", line 723, in block_container_layout
  File "weasyprint\layout\block.py", line 525, in _in_flow_layout
  File "weasyprint\layout\block.py", line 59, in block_level_layout
  File "weasyprint\layout\block.py", line 82, in block_level_layout_switch
  File "weasyprint\layout\flex.py", line 170, in flex_layout
AttributeError: 'FlexBox' object has no attribute 'replacement'
[PYI-22448:ERROR] Failed to execute script '__main__' due to unhandled exception!

```

**Comment by liZe** [comment]
I can reproduce, thanks.

**Comment by liZe** [comment]
It’s now fixed and tested, feedback is welcome!

**Comment by gokulprathin8** [comment]
could you please push the latest build to pypi as well? thanks!

**Comment by liZe** [comment]
> could you please push the latest build to pypi as well? thanks!

It will be included in version 65.1. Until then, you can downgrade to 64 or install current main branch with `pip install git+https://github.com/Kozea/WeasyPrint.git`.
