### ISSUE TITLE
SVG emoji rendering crashes with AttributeError: 'Stream' object has no attribute 'font_config' in v67.0

### ISSUE THREAD

**Issue by charles1018** [Kozea/WeasyPrint#2639]
## Description

WeasyPrint v67.0 crashes when rendering documents containing SVG emoji fonts. This is a regression from v66.0 where emoji rendering worked correctly.

## Steps to Reproduce

```python
from weasyprint import HTML

html_content = """
<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"></head>
<body>
  <p>Hello 😊 World 🎉</p>
</body>
</html>
"""

HTML(string=html_content).write_pdf("output.pdf")
```

## Expected Behavior

PDF should be generated with emoji characters rendered correctly (as it works in v66.0).

## Actual Behavior

Crashes with:
```
AttributeError: 'Stream' object has no attribute 'font_config'
```

Full traceback:
```
File "weasyprint/draw/text.py", line 237, in draw_first_line
    image = SVGImage(tree, None, None, stream)
File "weasyprint/images.py", line 259, in __init__
    font_config = context.font_config if context else None
AttributeError: 'Stream' object has no attribute 'font_config'
```

## Environment

- WeasyPrint version: 67.0
- Python version: 3.12
- OS: Windows 11 (also reproducible concept applies to all platforms)
- Pango version: 1.54

## Root Cause Analysis

In v67.0, `SVGImage.__init__` was modified to access `context.font_config`:

**v66.0 (working):**
```python
# weasyprint/images.py
class SVGImage:
    def __init__(self, tree, base_url, url_fetcher, context):
        self._svg = SVG(tree, base_url)  # No font_config access
```

**v67.0 (broken):**
```python
# weasyprint/images.py  
class SVGImage:
    def __init__(self, tree, base_url, url_fetcher, context):
        font_config = context.font_config if context else None  # NEW LINE
        self._svg = SVG(tree, base_url, font_config)
```

However, the call site in `draw/text.py` was not updated:
```python
# weasyprint/draw/text.py line 237
image = SVGImage(tree, None, None, stream)  # stream has no font_config!
```

The `stream` parameter is a `pydyf.Stream` object, not a context object with `font_config` attribute.

## Suggested Fix

Either:
1. Pass `None` instead of `stream` if font_config is not needed for inline emoji SVGs
2. Or pass a proper context object that has the `font_config` attribute

**Comment by liZe** [comment]
Thanks for the bug report.

It’s a duplicate of #2619.
