### ISSUE TITLE
weasyprint v53 regression - AttributeError: 'SVGImage' object has no attribute 'intrinsic_ratio'

### ISSUE THREAD

**Issue by br-cpvc** [Kozea/WeasyPrint#1421]
After updating weasyprint from 52.5 (and/or 53b2) to 53 and trying to convert the following example:

```
cat foo.html 
<html>
  <body>
    <table>
      <tr>
        <td><img style="width: 95%" src="foo.svg"></td>
      </tr>
    <table>
  </body>
</html>

cat foo.svg 
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
   xmlns:dc="http://purl.org/dc/elements/1.1/"
   xmlns:cc="http://creativecommons.org/ns#"
   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
   xmlns:svg="http://www.w3.org/2000/svg"
   xmlns="http://www.w3.org/2000/svg"
   viewBox="0 0 210 297">
</svg>
```

I now get the following error:
```
  File "/usr/bin/html_to_pdf.py", line 6, in convert
    HTML(infile).write_pdf(outfile, presentational_hints=True)
  File "/opt/miniconda/miniconda3/lib/python3.9/site-packages/weasyprint/__init__.py", line 180, in write_pdf
    self.render(
  File "/opt/miniconda/miniconda3/lib/python3.9/site-packages/weasyprint/__init__.py", line 134, in render
    return Document._render(
  File "/opt/miniconda/miniconda3/lib/python3.9/site-packages/weasyprint/document.py", line 885, in _render
    [Page(page_box) for page_box in page_boxes],
  File "/opt/miniconda/miniconda3/lib/python3.9/site-packages/weasyprint/document.py", line 885, in <listcomp>
    [Page(page_box) for page_box in page_boxes],
  File "/opt/miniconda/miniconda3/lib/python3.9/site-packages/weasyprint/layout/__init__.py", line 124, in layout_document
    pages = list(make_all_pages(context, root_box, html, pages))
  File "/opt/miniconda/miniconda3/lib/python3.9/site-packages/weasyprint/layout/pages.py", line 802, in make_all_pages
    page, resume_at = remake_page(i, context, root_box, html)
  File "/opt/miniconda/miniconda3/lib/python3.9/site-packages/weasyprint/layout/pages.py", line 739, in remake_page
    page, resume_at, next_page = make_page(
  File "/opt/miniconda/miniconda3/lib/python3.9/site-packages/weasyprint/layout/pages.py", line 549, in make_page
    root_box, resume_at, next_page, _, _ = block_level_layout(
  File "/opt/miniconda/miniconda3/lib/python3.9/site-packages/weasyprint/layout/blocks.py", line 58, in block_level_layout
    return block_level_layout_switch(
  File "/opt/miniconda/miniconda3/lib/python3.9/site-packages/weasyprint/layout/blocks.py", line 72, in block_level_layout_switch
    return block_box_layout(
  File "/opt/miniconda/miniconda3/lib/python3.9/site-packages/weasyprint/layout/blocks.py", line 126, in block_box_layout
    block_container_layout(
  File "/opt/miniconda/miniconda3/lib/python3.9/site-packages/weasyprint/layout/blocks.py", line 517, in block_container_layout
    collapsing_through) = block_level_layout(
  File "/opt/miniconda/miniconda3/lib/python3.9/site-packages/weasyprint/layout/blocks.py", line 58, in block_level_layout
    return block_level_layout_switch(
  File "/opt/miniconda/miniconda3/lib/python3.9/site-packages/weasyprint/layout/blocks.py", line 72, in block_level_layout_switch
    return block_box_layout(
  File "/opt/miniconda/miniconda3/lib/python3.9/site-packages/weasyprint/layout/blocks.py", line 126, in block_box_layout
    block_container_layout(
  File "/opt/miniconda/miniconda3/lib/python3.9/site-packages/weasyprint/layout/blocks.py", line 517, in block_container_layout
    collapsing_through) = block_level_layout(
  File "/opt/miniconda/miniconda3/lib/python3.9/site-packages/weasyprint/layout/blocks.py", line 58, in block_level_layout
    return block_level_layout_switch(
  File "/opt/miniconda/miniconda3/lib/python3.9/site-packages/weasyprint/layout/blocks.py", line 72, in block_level_layout_switch
    return block_box_layout(
  File "/opt/miniconda/miniconda3/lib/python3.9/site-packages/weasyprint/layout/blocks.py", line 126, in block_box_layout
    block_container_layout(
  File "/opt/miniconda/miniconda3/lib/python3.9/site-packages/weasyprint/layout/blocks.py", line 517, in block_container_layout
    collapsing_through) = block_level_layout(
  File "/opt/miniconda/miniconda3/lib/python3.9/site-packages/weasyprint/layout/blocks.py", line 58, in block_level_layout
    return block_level_layout_switch(
  File "/opt/miniconda/miniconda3/lib/python3.9/site-packages/weasyprint/layout/blocks.py", line 72, in block_level_layout_switch
    return block_box_layout(
  File "/opt/miniconda/miniconda3/lib/python3.9/site-packages/weasyprint/layout/blocks.py", line 121, in block_box_layout
    table_wrapper_width(
  File "/opt/miniconda/miniconda3/lib/python3.9/site-packages/weasyprint/layout/tables.py", line 738, in table_wrapper_width
    auto_table_layout(context, wrapper, containing_block)
  File "/opt/miniconda/miniconda3/lib/python3.9/site-packages/weasyprint/layout/tables.py", line 631, in auto_table_layout
    table_and_columns_preferred_widths(context, box, outer=False)
  File "/opt/miniconda/miniconda3/lib/python3.9/site-packages/weasyprint/layout/preferred.py", line 466, in table_and_columns_preferred_widths
    min_content_width(context, cell))
  File "/opt/miniconda/miniconda3/lib/python3.9/site-packages/weasyprint/layout/preferred.py", line 45, in min_content_width
    return table_cell_min_content_width(context, box, outer)
  File "/opt/miniconda/miniconda3/lib/python3.9/site-packages/weasyprint/layout/preferred.py", line 231, in table_cell_min_content_width
    children_widths = [
  File "/opt/miniconda/miniconda3/lib/python3.9/site-packages/weasyprint/layout/preferred.py", line 232, in <listcomp>
    min_content_width(context, child, outer=True)
  File "/opt/miniconda/miniconda3/lib/python3.9/site-packages/weasyprint/layout/preferred.py", line 52, in min_content_width
    return inline_min_content_width(
  File "/opt/miniconda/miniconda3/lib/python3.9/site-packages/weasyprint/layout/preferred.py", line 204, in inline_min_content_width
    widths = list(widths)
  File "/opt/miniconda/miniconda3/lib/python3.9/site-packages/weasyprint/layout/preferred.py", line 327, in inline_line_widths
    lines = [0, max_content_width(context, child), 0]
  File "/opt/miniconda/miniconda3/lib/python3.9/site-packages/weasyprint/layout/preferred.py", line 82, in max_content_width
    return replaced_max_content_width(box, outer)
  File "/opt/miniconda/miniconda3/lib/python3.9/site-packages/weasyprint/layout/preferred.py", line 695, in replaced_max_content_width
    return adjust(box, outer, width)
  File "/opt/miniconda/miniconda3/lib/python3.9/site-packages/weasyprint/layout/preferred.py", line 169, in adjust
    fixed = min_max(box, width)
  File "/opt/miniconda/miniconda3/lib/python3.9/site-packages/weasyprint/layout/preferred.py", line 122, in min_max
    ratio = box.replacement.intrinsic_ratio
AttributeError: 'SVGImage' object has no attribute 'intrinsic_ratio'
```

**Comment by liZe** [comment]
Hello!

Thank you for this report. The bug has already been reported in #1417 and fixed in `master`.
