### ISSUE TITLE
Unicode ranges throw an error in version 68

### ISSUE THREAD

**Issue by guneemwelloeux** [Kozea/WeasyPrint#2678]
When adding fonts, if the font is configured with unicode ranges, an error is raised.
The error showed up when I upgraded from v60 to v68. All was working properly in v60.

Error:
```
Traceback (most recent call last):
  File "...repro.py", line 13, in <module>
    font_config.add_font_face(font, url_fetcher=default_url_fetcher)
  File "...lib/python3.12/site-packages/weasyprint/text/fonts.py", line 233, in add_font_face
    for value in (unicode_range.start, unicode_range.end):
                  ^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'start'
```

Reproducer:
```
from weasyprint import default_url_fetcher
from weasyprint.text.fonts import FontConfiguration

font = {
    "font_family": "Cedarville Cursive",
    "font_weight": 400,
    "font_style": "normal",
    "src": [("external", "https://fonts.gstatic.com/s/cedarvillecursive/v18/yYL00g_a2veiudhUmxjo5VKkoqA-B_nuIrpw4cNOTw.woff2")],
    "unicode_range": ["U+0000-00FF", "U+0131", "U+0152-0153", "U+02BB-02BC", "U+02C6", "U+02DA", "U+02DC", "U+0304", "U+0308", "U+0329", "U+2000-206F", "U+20AC", "U+2122", "U+2191", "U+2193", "U+2212", "U+2215", "U+FEFF", "U+FFFD"]
}

font_config = FontConfiguration()
font_config.add_font_face(font, url_fetcher=default_url_fetcher)
```

**Comment by liZe** [comment]
Hi!

There’s [no public API](https://doc.courtbouillon.org/weasyprint/stable/api_reference.html#weasyprint.text.fonts.FontConfiguration) for `FontConfiguration`, you can’t rely on this function. You should really [use the `CSS` class](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#instantiating-html-and-css-objects) to add external fonts instead.

**Comment by liZe** [comment]
@guneemwelloeux did you manage to get what you wan with the `CSS` class?

**Comment by guneemwelloeux** [comment]
@liZe Yes I did, thanks. It took me longer than expected, mostly because of the dive into years old, never modified code.

I had to implement a custom "LocalFontFetcher" to deal with proprietary fonts available only in a side-car folder, and also fine tuning the attributes to URLFetcher to deal with the recently discovered vuln (which is why I upgraded in the first place).

Everything seems to be working well with the proper implementation.

It might be good, for the community, to add some documentation about that, but I was able to figure it out eventually.

**Comment by liZe** [comment]
> Everything seems to be working well with the proper implementation.

Good to know!

> It might be good, for the community, to add some documentation about that, but I was able to figure it out eventually.

> I had to implement a custom "LocalFontFetcher" to deal with proprietary fonts available only in a side-car folder

Can’t you use a `file://` URL for these fonts? (Or even a custom URL protocol, easier to handle in the URL fetcher if you want to disable other disk access.)

Our goal is to cover most cases with `CSS` and a custom URL fetcher, which are public API. If you have a use case that can’t work with that, I’d be happy to discuss it!

**Comment by liZe** [comment]
@guneemwelloeux Hi! Did you find the time to test `file://` URLs?
