### ISSUE TITLE
TypeError: HTMLUnicodeInputStream.__init__() got an unexpected keyword argument 'override_encoding'

### ISSUE THREAD

**Issue by igcherkaev** [Kozea/WeasyPrint#2701]
Hello,

weasyprint 68.0 and 68.1 has a bug.

```py
from weasyprint import HTML, CSS


if __name__ == "__main__":
    rendered = "<html></html>"
    HTML(string=rendered, encoding='utf-8')

```

leads to:

```
Traceback (most recent call last):
  File "/home/user/.config/JetBrains/PyCharm2025.3/scratches/scratch_19.py", line 6, in <module>
    HTML(string=rendered, encoding='utf-8')
  File "/home/user/PycharmProjects/weasyprint-bug/venv/lib/python3.11/site-packages/weasyprint/__init__.py", line 178, in __init__
    result = tinyhtml5.parse(file_obj, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/PycharmProjects/weasyprint-bug/venv/lib/python3.11/site-packages/tinyhtml5/parser.py", line 56, in parse
    return HTMLParser(namespace_html_elements).parse(document, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/PycharmProjects/weasyprint-bug/venv/lib/python3.11/site-packages/tinyhtml5/parser.py", line 203, in parse
    self._parse(stream, **kwargs)
  File "/home/user/PycharmProjects/weasyprint-bug/venv/lib/python3.11/site-packages/tinyhtml5/parser.py", line 74, in _parse
    self.tokenizer = HTMLTokenizer(stream, parser=self, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/PycharmProjects/weasyprint-bug/venv/lib/python3.11/site-packages/tinyhtml5/tokenizer.py", line 42, in __init__
    self.stream = HTMLInputStream(stream, **kwargs)  # HTMLInputStream object
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/PycharmProjects/weasyprint-bug/venv/lib/python3.11/site-packages/tinyhtml5/inputstream.py", line 44, in HTMLInputStream
    return HTMLUnicodeInputStream(source, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: HTMLUnicodeInputStream.__init__() got an unexpected keyword argument 'override_encoding'
```

**Comment by liZe** [comment]
Hi!

It really looks like #2664. Do you use the latest version of tinyhtml5?

**Comment by igcherkaev** [comment]
> Hi!
> 
> It really looks like [#2664](https://github.com/Kozea/WeasyPrint/issues/2664). Do you use the latest version of tinyhtml5?

Yeah it does, sorry, my bad, somehow it didn't show me that such issue had already existed. I didn't install or had any specific version of tinyhtml5 in the requirements.txt, so whatever it came with as a dependency. Apparently, pip kept tinyhtml 2.0.0 after upgrading the weasyprint library to 68.1 or 68.0.

```
Requires-Dist: tinyhtml5 >=2.0.0b1
```
it has this in its METADATA. So, yeah, I dunno :) Manually uninstalling tinyhtml5 from the project and re-installing from requirements.txt helps, it brings tinyhtml5 2.1.0 with it.

**Comment by liZe** [comment]
> Yeah it does, sorry, my bad, somehow it didn't show me that such issue had already existed.

No problem!

> Apparently, pip kept tinyhtml 2.0.0 after upgrading the weasyprint library to 68.1 or 68.0.

Yes, 2.0.0 works as long as the encoding is not given when using strings, as it’s useless (there’s no need to decode a string). Pip doesn’t recursively update dependencies when it’s not needed.
