### ISSUE TITLE
TypeError: Stream.set_color_rgb() missing 1 required positional argument: 'b'

### ISSUE THREAD

**Issue by ryanwang520** [Kozea/WeasyPrint#1996]
```python
from weasyprint import HTML
html_str = """<body>

<table style="border-collapse: collapse; width: 100%; height: 156px; border-color: #000000;" border="1">
<tbody>
<tr style="height: 26px;">
<td style="width: 7.043051359516616%; height: 26px;"><strong>QTY</strong></td>
</tr>
</tbody>
</table>

</body>
"""
html = HTML(string=html_str)
main_doc = html.render(presentational_hints=True)
main_doc.write_pdf()

```

The code above will cause a runtime TypeError ` Stream.set_color_rgb() missing 1 required positional argument: 'b'
` in Weasyprint 60.0.

 I tested that the same code works in version 59.0 so I suspect it could be a regression.

**Comment by liZe** [comment]
Thanks a lot for the detailed report 💜 .

> I tested that the same code works in version 59.0 so I suspect it could be a regression.

You’re right, that’s a regression introduced by 8b2047c. Let’s fix this!
