### ISSUE TITLE
Page failes with 'AttributeError: 'NoneType' object has no attribute 'children'' when using 66.0 - works with 65.1

### ISSUE THREAD

**Issue by EugenMayer** [Kozea/WeasyPrint#2571]
Page works with 65.1 (and before), after upgrading to 66.0 we get the exception:

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/weasyprint/wsgi.py", line 38, in generate
    pdf = write_pdf(HTML(string=request.data, encoding='utf-8'))
  File "/weasyprint/print_converter.py", line 13, in write_pdf
    document = toc_inject_page_numbers_into_toc_table(html)
  File "/weasyprint/print_converter.py", line 33, in toc_inject_page_numbers_into_toc_table
    document: Document = render_document(html)
  File "/weasyprint/print_converter.py", line 21, in render_document
    return html.render(stylesheets=[CSS('css/local.css')], presentational_hints=True)
  File "/usr/local/lib/python3.10/dist-packages/weasyprint/__init__.py", line 225, in render
    return Document._render(self, font_config, counter_style, options)
  File "/usr/local/lib/python3.10/dist-packages/weasyprint/document.py", line 253, in _render
    [Page(page_box) for page_box in page_boxes],
  File "/usr/local/lib/python3.10/dist-packages/weasyprint/document.py", line 253, in <listcomp>
    [Page(page_box) for page_box in page_boxes],
  File "/usr/local/lib/python3.10/dist-packages/weasyprint/layout/__init__.py", line 130, in layout_document
    pages = list(make_all_pages(context, root_box, html, pages))
  File "/usr/local/lib/python3.10/dist-packages/weasyprint/layout/page.py", line 994, in make_all_pages
    page, resume_at = remake_page(i, page_groups, context, root_box, html)
  File "/usr/local/lib/python3.10/dist-packages/weasyprint/layout/page.py", line 934, in remake_page
    page, resume_at, next_page = make_page(
  File "/usr/local/lib/python3.10/dist-packages/weasyprint/layout/page.py", line 673, in make_page
    root_box.children = out_of_flow_boxes + root_box.children
AttributeError: 'NoneType' object has no attribute 'children'
```

 How could i find out which portion is responsible so you have a reproducer?

**Comment by liZe** [comment]
Hi!

Thanks for the report.

The problem probably comes from floats at the root of the document. Could you please share a HTML/CSS sample that shows the problem? (By mail if you can’t share it publicly.)

**Comment by EugenMayer** [comment]
Sorry for being late, issue lost on my radar :)

[printtest.html](https://github.com/user-attachments/files/22881062/printtest.html)

This is the reproducer HTML, 65.1 works, 66.0 does not

**Comment by EugenMayer** [comment]
@liZe anything else i could help you with / provide for a better understanding of the issue / env?

**Comment by liZe** [comment]
The problem is triggered by `.content { min-height: 334.22mm }` that makes the only body child higher than the whole page. We have to find a way to handle this.

**Comment by liZe** [comment]
There are actually 2 different issues:
- The crash happens when the main normal flow container is higher than the page, with a float split between two pages. In this case, with `.content { min-height: 334.22mm }`, nothing is rendered in the main flow and we get `None` instead of a parent box. Forcing to render something fixes the problem.
- The page is still empty if we force the rendering, even if there’s a lot of space below the floating element. It happens when the original float container creates a CSS stacking context, in this document because of `.content { display: flow-root }`.

@EugenMayer I’ll open a pull request for the first issue. For the second one, I have to go deeper to understand what’s going on.

**Comment by EugenMayer** [comment]
thank you a lot @liZe - let me know if i can provide anything.

We control the entire HTML rendering process and could basically change most of the things here - the question here is, is it a print engine issue or a html violation by the html pipeline. Let me know your thoughts on this.

Thanks for the effort!

**Comment by liZe** [comment]
(As a side note: the bug was introduced by #2459.)

> thank you a lot [@liZe](https://github.com/liZe) - let me know if i can provide anything.

Thanks, I think I have everything I need.

> We control the entire HTML rendering process and could basically change most of the things here - the question here is, is it a print engine issue or a html violation by the html pipeline. Let me know your thoughts on this.

This is a bug in WeasyPrint, not in your HTML or CSS files. The `.content { min-height: 334.22mm }` rule is a bit strange for pagination and could cause different renderings depending on the rendering engine you use, as I’m not sure that the case is actually specified. But we shouldn’t get the crash (obviously), and we shouldn’t get the empty page when we avoid the crash.

**Comment by liZe** [comment]
Hello @EugenMayer,

#2586 should fix this issue!

**Comment by EugenMayer** [comment]
@liZe not sure our 'from source' dev statck for weazysprint is still working, of so. i try your PR to validate it if it helps.

Thank you for your effort!

**Comment by EugenMayer** [comment]
@liZe just tested 67.0.0 and indeed, it did solve the issue. Thank you for the effort!

**Comment by liZe** [comment]
> Thank you for the effort!

@EugenMayer Thank you for the feedback!
